### ISSUE TITLE
Add picture to the readme file

### ISSUE THREAD

**Issue by DarekRepos** [DarekRepos/crane-404-error-page#7]
Link directly to the raw version of an image that is stored in this repository.

**Comment by sidhartha2002** [comment]
**Hey Bro if I am not wrong, are you asking to add the webpage image  in the readme file so that if someone visit the repo they can redirect to that webpage if that image is clicked ?
If so I will definately do accordingly if you assign me the task under the label `Hacktoberfest`.** 
Thanks.

**Comment by DarekRepos** [comment]
Yes, this is exactly what i want to create,  i think a picture is probably be better enhancement . 
If you steel want to do this i assigned you this task, feel free to do it.
Thanks!
